site_name: Citiwatts Wiki
site_url: https://github.com/citiwatts/wiki/
repo_url: https://github.com/citiwatts/wiki/wiki
edit_uri_template: '{path_noext}/_edit'  # https://www.mkdocs.org/user-guide/configuration/#edit_uri_template
hooks:
  - change_edit_url.py
  - add_id_to_first_h1.py
extra_css:
  - custom.css
markdown_extensions:
  - pymdownx.magiclink  # Convert bare URLs into hyperlinks
  - attr_list  # Allow setting attributes on block elements
  - pymdownx.arithmatex: # Allow LaTeX equations
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
extra:
  generator: false  # Hide "Made with Material for MkDocs"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/citiwatts/
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: https://raw.githubusercontent.com/citiwatts/wiki/refs/heads/main/assets/logo-mini.png
  logo: https://raw.githubusercontent.com/citiwatts/wiki/refs/heads/main/assets/logo-mini.png
  icon:
    repo: fontawesome/brands/github
    # edit: material/file-edit-outline
  features:
    - content.action.edit  # Show Edit Page
    - navigation.top  # Show "Back to Top" on scrolling
    # - navigation.expand  # Expand left menu sections
    - navigation.footer  # Show footer navigation
  user_color_mode_toggle: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# nav:
#   - For Authors:
#     - Create New Page: https://github.com/coollife-project/wiki/wiki/_new

nav:
  - Wiki Introduction:
    - home.md
     <!--- - welcome-page.md --->
    - about-the-citiwatts-toolbox.md
  - General Functionalities & Structure:
    - introduction-to-user-interface.md
    - user-account-registration-log-in-personal-layer-management.md
    - layer-section-in-the-citiwatts-toolbox.md
    - select-a-region-in-the-citiwatts-toolbox.md
    - retrieve-indicators-of-a-selected-area.md
    - access-to-calculation-modules.md
    - database-behind-the-citiwatts-toolbox.md
    - data-upload-functionalities.md
    - data-export-functionalities.md
    - platform-release-notes.md
  - Datasets / Layers:
    - methodology-of-data-collection.md
    - open-data-repository.md
  - Calculation Modules (CMs):
    - Heat Calculation Modules (CMs):
      - heat-cm-customized-heat-and-gross-floor-area-density-maps.md
      - heat-cm-scale-heat-and-cool-density-maps.md
      - heat-cm-demand-projection.md
      - heat-cm-heat-load-profiles.md
      - heat-cm-district-heating-potential-areas-user-defined-thresholds.md
      - heat-cm-district-heating-potential-economic-assessment.md
      - heat-cm-district-heating-potential-economic-assessment--with-temperature-levels.md
      - heat-cm-district-heating-supply.md
      - heat-cm-decentral-heating-supply.md
      - heat-cm-scenario-assessment.md
    - Cooling Calculation Modules (CMs):
      - cooling-cm-district-cooling.md
    - Energy Sources Calculation Modules (CMs):
      - energy-sources-cm-solar-thermal-and-pv-potential.md
      - energy-sources-cm-shallow-geothermal-potential.md
      - energy-sources-cm-heat-source-potential.md
      - energy-sources-cm-biomass-potential.md
      - energy-sources-cm-wind-potential.md
      - energy-sources-cm-excess-heat-transport-potential.md
    - Industry Calculation Modules (CMs):
      - industry-cm-add-industry-plant.md
    - Mobility Calculation Modules (CMs):
      - mobility-cm-electric-vehicle-density.md
      - mobility-cm-electric-vehicles-charging-needs.md
    - Energy System Calculation Modules (CMs):
      - energy-system-cm-energyplan.md
  - Learning Center:
    - guideline-citiwatts-toolbox-on-local-level.md
    - guideline-heat-planning-toolchain.md
    - guideline-district-cooling-toolchain.md
    - guideline-mobility-toolchain.md
    - training-materials.md
    - case-study-reports.md
  - For Developers:
    - how-to-edit-this-wiki.md
    - developers-section.md
    - api.md
    - layers-available.md
    - example-of-charts.md
