site_name: CoolLIFE Project Wiki
site_url: https://github.com/coollife-project/wiki/
repo_url: https://github.com/coollife-project/wiki/wiki
edit_uri: ./_edit
hooks:
  - change_edit_url.py
extra:
  generator: false  # Hide "Made with Material for MkDocs"
markdown_extensions:
  - pymdownx.magiclink  # converts bare URLs into hyperlinks
plugins:
  - search
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: https://raw.githubusercontent.com/coollife-project/.github/main/logo.png
  logo: https://raw.githubusercontent.com/coollife-project/.github/main/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit  # Show Edit Page
    - navigation.top  # Show "Back to Top" on scrolling
  user_color_mode_toggle: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: light blue
      primary: indigo
      accent: indigo
      # primary: #0AA7B8  # hotmaps cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode  
